### ISSUE TITLE
ModuleNotFoundError: No module named 'vlkit.homography'

### ISSUE THREAD

**Issue by wangle53** [zeakey/bezier-palm#1]
Hello, when i run your synthesize2d.py, the below error occured, 'ModuleNotFoundError: No module named 'vlkit.homography''. I have no idea about that. By the way, when will you release the 3D code? Thanks.

**Comment by zeakey** [comment]
I've updated `vlkit` and please reinstall via `pip uninstall vlkit && pip install git+https://github.com/vlkit/vlkit.git@master`.
Actually, homography is not used by default, you can simply comment relavent codes instead.

Currently, we do NOT have the timeline to release the 3d synthesis codes.

**Comment by wangle53** [comment]
It works, Thank you very much.
