### ISSUE TITLE
perspective_transformation

### ISSUE THREAD

**Issue by Leesule667** [zeakey/bezier-palm#2]
Could you tell me if the function random_perspective_matrix() in the code from vlkit.geometry.homography import random_perspective_matrix is your own creation? I couldn't find this function in the latest version library of vlkit.

**Comment by zeakey** [comment]
Actually the perspective_transformation wasn't used in our method. That being said, you can simply comment that line.

We experimented with it and it didn't work. If you really want to use it anyway, install vlkit from source here: <https://github.com/vlkit/vlkit/blob/master/vlkit/geometry/perspective.py>

**Comment by Leesule667** [comment]
> 实际上我们的方法中没有使用 perspective_transformation。话虽这么说，您可以简单地评论该行。
> 
> 我们对此进行了试验，但没有奏效。如果您真的想使用它，请在此处从源代码安装 vlkit：[https ://github.com/vlkit/vlkit/blob/master/vlkit/geometry/perspective.py](https://github.com/vlkit/vlkit/blob/master/vlkit/geometry/perspective.py)

Thank you for your answer. It was a great help and much appreciated.

**Comment by Leesule667** [comment]
> Actually the perspective_transformation wasn't used in our method. That being said, you can simply comment that line.
> 
> We experimented with it and it didn't work. If you really want to use it anyway, install vlkit from source here: https://github.com/vlkit/vlkit/blob/master/vlkit/geometry/perspective.py

Thank you for your answer. It was a great help and much appreciated.
